schedules:
- cron: '30 3 * * *'
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml
  displayName: 'Daily build at 3:30 AM'
  branches:
    include:
    - master
    
    
variables:
  NUGET_VERSION: 0.1
  PS1_TROUBLE_SHOOT: On
  # Short name is critical for 2017 and older
  PS1_REPO_DOWNLOAD_FOLDER_1: 'B:\SQL-Media'
  PS1_REPO_DOWNLOAD_FOLDER_2: 'D:\SQL-Media'
  PS1_REPO_DOWNLOAD_FOLDER_3: 'C:\SQL-Media'

trigger:
  branches:
    include:
    - manual

jobs:

- job: Install
  displayName: '→'
  pool:
    vmImage: '$(IMAGE)'
  timeoutInMinutes: 180
  cancelTimeoutInMinutes: 7
  strategy:
    maxParallel: 10
    matrix:
      '#26 [2012-x64 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x64 LocalDB'
      '#30 [2014-x86 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x86 LocalDB'
      '#33 [2014-x64 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x64 LocalDB'
      '#37 [2016 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 LocalDB'
      '#58 [2022 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 LocalDB'
      '#39 [2016 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 Core Update'
      '#64 [2022 Developer Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 Developer Update'
      '#16 [2008R2-x86 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x86 Developer'
      '#21 [2008R2-x64 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x64 Developer'
      '#25 [2012-x86 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x86 Developer'
      '#29 [2012-x64 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x64 Developer'
      '#36 [2014-x64 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x64 Developer'

      '#05 [2008-x86 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x86 Core Update'

      '#03 [2005-x86 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2005-x86 Advanced Update'
      '#12 [2008R2-x86 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x86 Core'
      '#13 [2008R2-x86 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x86 Core Update'
      '#14 [2008R2-x86 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x86 Advanced'
      '#15 [2008R2-x86 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x86 Advanced Update'
      '#17 [2008R2-x64 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x64 Core'
      '#18 [2008R2-x64 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x64 Core Update'
      '#19 [2008R2-x64 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x64 Advanced'
      '#20 [2008R2-x64 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008R2-x64 Advanced Update'

      '#01 [2005-x86 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2005-x86 Core'
      '#02 [2005-x86 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2005-x86 Advanced'
      '#04 [2008-x86 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x86 Core'
      '#06 [2008-x86 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x86 Advanced'
      '#07 [2008-x86 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x86 Advanced Update'
      '#08 [2008-x64 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x64 Core'
      '#09 [2008-x64 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x64 Core Update'
      '#10 [2008-x64 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x64 Advanced'
      '#11 [2008-x64 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2008-x64 Advanced Update'
      '#22 [2012-x86 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x86 LocalDB'
      '#23 [2012-x86 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x86 Core'
      '#24 [2012-x86 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x86 Advanced'
      '#27 [2012-x64 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x64 Core'
      '#28 [2012-x64 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2012-x64 Advanced'
      '#31 [2014-x86 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x86 Core'
      '#32 [2014-x86 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x86 Advanced'
      '#34 [2014-x64 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x64 Core'
      '#35 [2014-x64 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2014-x64 Advanced'
      '#38 [2016 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 Core'
      '#40 [2016 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 Advanced'
      '#41 [2016 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 Advanced Update'
      '#42 [2016 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 Developer'
      '#43 [2016 Developer Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2016 Developer Update'
      '#44 [2017 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 LocalDB'
      '#45 [2017 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 Core'
      '#46 [2017 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 Core Update'
      '#47 [2017 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 Advanced'
      '#48 [2017 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 Advanced Update'
      '#49 [2017 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 Developer'
      '#50 [2017 Developer Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2017 Developer Update'
      '#51 [2019 LocalDB]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 LocalDB'
      '#52 [2019 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 Core'
      '#53 [2019 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 Core Update'
      '#54 [2019 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 Advanced'
      '#55 [2019 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 Advanced Update'
      '#56 [2019 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 Developer'
      '#57 [2019 Developer Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2019 Developer Update'
      '#59 [2022 Core]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 Core'
      '#60 [2022 Core Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 Core Update'
      '#61 [2022 Advanced]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 Advanced'
      '#62 [2022 Advanced Update]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 Advanced Update'
      '#63 [2022 Developer]':
             IMAGE: 'windows-2019'
             SQL_SERVERS: '2022 Developer'

  steps:

  - powershell: |
      Write-Host "CPU: $((Get-WmiObject Win32_Processor).Name), $([System.Environment]::ProcessorCount) Cores"

      gdr -PSProvider 'FileSystem'
    displayName: 'Bootstrap'

  - powershell: |
       cd Scripts
       powershell -f Uninstall-LocalDB.ps1
    condition: contains(variables['SQL_SERVERS'], 'LocalDB')
    displayName: 'Uninstall LocalDB'

  - powershell: |
       $ENV:DEBUG_LOG_FOLDER = "$($ENV:SYSTEM_ARTIFACTSDIRECTORY)"
       cd Scripts
       powershell -f Setup-SqlServers.ps1 -SqlServers "$($ENV:SQL_SERVERS)" *| tee "$($ENV:SYSTEM_ARTIFACTSDIRECTORY)\FULL-LOG.txt"
       get-wmiobject win32_service | where {$_.Name.ToLower().IndexOf("sql") -ge 0 -or $_.Name -match "browser" -or $_.DisplayName -match "browser"  } | sort-object -Property "DisplayName" | ft State, Name, DisplayName, StartMode, StartName
       # Install-Module -Force Platform-Info
    condition: succeededOrFailed()
    displayName: 'Install'

  - powershell: |
       get-wmiobject win32_service | where {$_.Name.ToLower().IndexOf("sql") -ge 0 } | sort-object -Property "DisplayName" | ft State, Name, DisplayName, StartMode, StartName
       cd Scripts
       powershell -f "[Test] Publish SQL Server Setup Logs.ps1" 
       gdr -PSProvider 'FileSystem'
    condition: succeededOrFailed()
    displayName: 'Publish Setup Logs'

  - powershell: |
       if (-not ("$($ENV:SQL_SERVERS)" -match "LocalDB")) {
         Remove-Item -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server Local DB\Installed Versions" -Recurse -Force -EA SilentlyContinue
       }
       
       cd Scripts
       & 7z.exe x LocalSqlDiscovery-net4.5.7z -oc:\Temp\ > $null
       cd c:\Temp\LocalSqlDiscovery-net4.5
       $outputFile = "SHOW-SQL-Servers.log"
       & .\SHOW-SQL-Servers.cmd *| tee "$outputFile"
       $mediumVersion = Get-Content "$outputFile" | ? {$_ -match "Medium Version"} | % {$_.Split(":") | Select -Last 1}
       $Utf8 = New-Object System.Text.UTF8Encoding $False
       $sqlDef = "{0,-33}" -f "$($ENV:SQL_SERVERS)"
       $mediumVersionFormatted = "{0,-77}" -f "$mediumVersion"
       [System.IO.File]::WriteAllLines("$($ENV:SYSTEM_ARTIFACTSDIRECTORY)\VERSION.LOG", "| $sqlDef | $mediumVersionFormatted |", $utf8)
       [System.IO.File]::WriteAllLines("$($ENV:SYSTEM_ARTIFACTSDIRECTORY)\Medium Version.txt", "$mediumVersion", $utf8)
       
       Get-WmiObject -class "Win32_PageFileUsage" -namespace "root\CIMV2" -computername localhost | Format-Table Caption, Name, PeakUsage, AllocatedBaseSize, CurrentUsage -AutoSize | Out-String -Width 256
    condition: succeededOrFailed()
    displayName: 'Show SQL Servers'

  - bash: |
      set -eu; set -o pipefail
      d=$PWD
      pushd "$(System.ARTIFACTSDIRECTORY)"
      # 7z a -mx=1 -ms=on -mqs=on "Source-$(Agent.JobName).7z" "$d"
      popd
    condition: succeededOrFailed()
    displayName: 'Prepare Artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'












- job: 'Combine'
  condition: succeededOrFailed()
  pool:
    vmImage: 'windows-2022'
  timeoutInMinutes: 30
  dependsOn:
    - Install

  steps: 

  - task: DownloadPipelineArtifact@2
    condition: succeededOrFailed()
    displayName: 'Download of all platforms to $(RAW_ARTIFACTS_DIR)'
    inputs:
      path: '$(SYSTEM.ARTIFACTSDIRECTORY)\All'
      patterns: 
        "**"
    
  - powershell: |
       cd $ENV:SYSTEM_ARTIFACTSDIRECTORY
       $reportLines = Get-ChildItem -Path "." -Filter "VERSION.LOG" -recurse -force | Sort-Object -Property FullName -Descending | % {$_.FullName} | % { 
         $dir = [System.IO.Path]::GetDirectoryName($_)
         $jsonFile = "$dir\SQL Setup Benchmark.json"
         $jsonString=[System.IO.File]::ReadAllText($jsonFile)
         $jsonObject = @($jsonString | ConvertFrom-Json) | Select -First 1
         $secondsInstall=$jsonObject.SecondsInstall
         $secondsDownload=$jsonObject.SecondsDownload
         $cpu=$jsonObject.Cpu
         $columns = [System.IO.File]::ReadAllText($_).Trim(@([char]13,[char]10)) 
         foreach($val in $secondsDownload, $secondsInstall, ($secondsDownload + $secondsInstall), $cpu) {
           $valFormatted = If ($val -is [decimal]) { (new-object DateTime(0)).Add([TimeSpan]::FromSeconds($val)).ToString("mm:ss.f").PadRight(9); } else { "$val".PadRight(50) }
           $columns += $valFormatted + " |"
         }
         "$columns"
       }
       $reportLines > FULL-REPORT.TXT
       & 7z @("a", "-sdel", "-mx=2", "-ms=on", "-mqs=on", "-xr!FULL-REPORT.TXT", "SQL Servers Combined.7z", "*");
    condition: succeededOrFailed()
    displayName: 'Prepare Artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(SYSTEM.ARTIFACTSDIRECTORY)'
      artifactName: 'SQL Servers Combined'
