variables:
  NUGET_VERSION: 0.1
  PS1_TROUBLE_SHOOT: On
  PS1_REPO_DOWNLOAD_FOLDER_1: 'C:\SQL-Downloads'

trigger:
  branches:
    include:
    - main

jobs:

- job: Download
  pool:
    vmImage: '$(IMAGE)'
  timeoutInMinutes: 120
  strategy:
    maxParallel: 4
    matrix:
      'on 2019':
        IMAGE: 'windows-2019'
      # 'on 2022':
      #  IMAGE: 'windows-2022'

  steps:

  - powershell: |
      Write-Host "CPU: $((Get-WmiObject Win32_Processor).Name), $([System.Environment]::ProcessorCount) Cores"

      gdr -PSProvider 'FileSystem'
      Get-Volume
      Get-PhysicalDisk
      Get-Partition

    displayName: 'Bootstrap'

  - powershell: |
       cd Scripts
       powershell -f "[Test] Download and Extract SQL Server Setup.ps1" *| tee "$($ENV:SYSTEM_ARTIFACTSDIRECTORY)\FULL-LOG.txt"
       gdr -PSProvider 'FileSystem'
    condition: succeededOrFailed()
    displayName: 'Install'

  - bash: |
      set -eu; set -o pipefail
      d=$PWD
      pushd "$(System.ARTIFACTSDIRECTORY)"
      7z a -mx=1 -ms=on -mqs=on "Source-$(Agent.JobName).7z" "$d"
      popd
    condition: succeededOrFailed()
    displayName: 'Prepare Artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'

