variables:
  NUGET_VERSION: 0.1
  PS1_TROUBLE_SHOOT: On

trigger:
  branches:
    include:
    - main

jobs:

- job: Install
  pool:
    vmImage: '$(IMAGE)'
  timeoutInMinutes: 100
  strategy:
    maxParallel: 4
    matrix:
      'Tiny on 2019':
        IMAGE: 'windows-2019'
        PGTYPE: tiny
      'Tiny on 2022':
        IMAGE: 'windows-2022'
        PGTYPE: tiny

  steps:

  - powershell: |
      $cpuName=(Get-WmiObject Win32_Processor).Name
      Write-Host "CPU: $($cpuName), $([System.Environment]::ProcessorCount) Cores"

    displayName: 'Bootstrap'

  - powershell: |
       cd Scripts
       powershell -f "[Test] Download and Extract SQL Server Setup.ps1" *| tee "$($ENV:SYSTEM_ARTIFACTSDIRECTORY)\FULL-LOG.txt"
    condition: succeededOrFailed()
    displayName: 'Install'

  - bash: |
      set -eu; set -o pipefail
      d=$PWD
      pushd "$(System.ARTIFACTSDIRECTORY)"
      7z a -mx=1 -ms=on -mqs=on "Source-$(Agent.JobName).7z" "$d"
      popd
    condition: succeededOrFailed()
    displayName: 'Prepare Artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'

