variables:
  NUGET_VERSION: 0.1
  PS1_TROUBLE_SHOOT: On
  # Short name is critical for 2017 and older
  PS1_REPO_DOWNLOAD_FOLDER_1: 'B:\SQL-Media'
  PS1_REPO_DOWNLOAD_FOLDER_2: 'D:\SQL-Media'
  PS1_REPO_DOWNLOAD_FOLDER_3: 'C:\SQL-Media'

trigger:
  branches:
    include:
    - main

jobs:

- job: Install
  pool:
    vmImage: '$(IMAGE)'
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 7
  strategy:
    maxParallel: 6
    matrix:
      '2005 on Server2022':
        IMAGE: 'windows-2022'
        TEST_SQL_VERSIONS: '2005'
        TEST_SQL_UPDATES: False
      '2022 2019 on Server2019':
        IMAGE: 'windows-2019'
        TEST_SQL_VERSIONS: '2022 2019'
        TEST_SQL_UPDATES: False
      '2017 on Server2019':
        IMAGE: 'windows-2019'
        TEST_SQL_VERSIONS: '2017'
        TEST_SQL_UPDATES: False
      '2016 on Server2019':
        IMAGE: 'windows-2019'
        TEST_SQL_VERSIONS: '2016'
        TEST_SQL_UPDATES: False
      '2014 2012 on Server2019':
        IMAGE: 'windows-2019'
        TEST_SQL_VERSIONS: '2014 2012'
        TEST_SQL_UPDATES: False
      '2008 2008R2 on Server2019':
        IMAGE: 'windows-2019'
        TEST_SQL_VERSIONS: '2008'
        TEST_SQL_UPDATES: False
      '2005 on Server2019':
        IMAGE: 'windows-2019'
        TEST_SQL_VERSIONS: '2005'
        TEST_SQL_UPDATES: False

  steps:

  - powershell: |
      Write-Host "CPU: $((Get-WmiObject Win32_Processor).Name), $([System.Environment]::ProcessorCount) Cores"

      gdr -PSProvider 'FileSystem'

    displayName: 'Bootstrap'

  - powershell: |
       cd Scripts
       powershell -f "[Test] Setup All The SQL Servers.ps1" *| tee "$($ENV:SYSTEM_ARTIFACTSDIRECTORY)\FULL-LOG.txt"
       gdr -PSProvider 'FileSystem'
       # Install-Module -Force Platform-Info
    condition: succeededOrFailed()
    displayName: 'Install'

  - powershell: |
       get-wmiobject win32_service | where {$_.Name.ToLower().IndexOf("sql") -ge 0 } | sort-object -Property "DisplayName" | ft State, Name, DisplayName, StartMode, StartName
       cd Scripts
       powershell -f "[Test] Publish SQL Server Setup Logs.ps1" 
       gdr -PSProvider 'FileSystem'
    condition: succeededOrFailed()
    displayName: 'Publish Setup Logs'

  - bash: |
      set -eu; set -o pipefail
      d=$PWD
      pushd "$(System.ARTIFACTSDIRECTORY)"
      7z a -mx=1 -ms=on -mqs=on "Source-$(Agent.JobName).7z" "$d"
      popd
    condition: succeededOrFailed()
    displayName: 'Prepare Artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'

